name: My First Workflow

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  my_first_job:
    name: First Job
    continue-on-error: true  #Continue to 2nd Job on any error
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: First Step
        run: echo "My first job ran successfully"

      - name: Display service.yaml
        run: cat service.yaml

  my_second_job:
    name: Second Job
    needs: my_first_job  #Needs First Job 
    runs-on: ubuntu-latest

    steps:
      - name: Second Step
        run: echo "My second job ran successfully"
