name: Manual Pipeline


on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main


jobs:

  build:

      runs-on: ubuntu-latest
      # runs-on: self-hosted

      steps:

      - name: Hello friends
        run: echo "Manual run"

      - name: PowerShell script
        uses: Amadevus/pwsh-script@v2.0.3
        with:
          script: |
                Write-Host "Shyam"
